# Theme Settings Configuration File
##
### use settings.yml file for configure colors, ui, rtl, sidebar, animation options

### Main Settings
settings:
  quick_colors: "" # select quick color schemes: "blue", "green", "orange", "pink", "purple", "red". If empty colors taken from _sass/ryancv/settings.scss
  dark_ui: 0 # activated dark ui styles
  rtl: 0 # activated rtl styles
  sidebar: 1 # for disable sidebar and sidebar button change to 0
  preloader: "loading..." # preloader loading text

### Portfolio Filters Settings
portfolio:
  filters:
    - name: "All"
      slug: "box-item"
      active: 1

    - name: "Python/R"
      slug: "f-python-and-r"
      active: 0

    - name: "Viz"
      slug: "f-viz"
      active: 0

    - name: "SQL"
      slug: "f-sql"
      active: 0

    - name: "NLP"
      slug: "f-nlp"
      active: 0

    - name: "Web App"
      slug: "f-webapp"
      active: 0

    - name: "Others"
      slug: "f-others"
      active: 0
